//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int IdOrder { get; set; }
        public int IdProduct { get; set; }
        public Nullable<int> Qty { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
